apiVersion: v2
name: guacamole
description: A Helm chart for Apache Guacamole - clientless remote desktop gateway
type: application
version: 1.0.0
appVersion: "1.6.0"
kubeVersion: ">=1.25.0-0"

home: https://guacamole.apache.org/
icon: https://guacamole.apache.org/images/logos/guac-tricolor-logo.svg

sources:
  - https://github.com/apache/guacamole-client
  - https://github.com/apache/guacamole-server

maintainers:
  - name: Maxime Wewer
    url: https://github.com/MaximeWewer/

keywords:
  - guacamole
  - remote-desktop
  - bastion
  - rdp
  - ssh
  - vnc
  - gateway
