{{- if and .Values.database.external.enabled (not .Values.database.external.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "guacamole.fullname" . }}-db-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "guacamole.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.database.external.password }}
  password: {{ .Values.database.external.password | b64enc | quote }}
  {{- else }}
  password: {{ randAlphaNum 16 | b64enc | quote }}
  {{- end }}
{{- end }}
