{{- if and .Values.sqlserver.enabled .Values.sqlserver.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "guacamole.fullname" . }}-sqlserver-data
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "guacamole.labels" . | nindent 4 }}
    app.kubernetes.io/component: sqlserver
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.sqlserver.persistence.storageClass }}
  storageClassName: {{ .Values.sqlserver.persistence.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.sqlserver.persistence.size }}
{{- end }}
