{{- if and .Values.sqlserver.enabled (not .Values.sqlserver.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "guacamole.fullname" . }}-sqlserver
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "guacamole.labels" . | nindent 4 }}
    app.kubernetes.io/component: sqlserver
type: Opaque
data:
  {{- $saPassword := .Values.sqlserver.auth.saPassword | default (randAlphaNum 16) }}
  {{- $password := .Values.sqlserver.auth.password | default (randAlphaNum 16) }}
  sa-password: {{ $saPassword | b64enc | quote }}
  password: {{ $password | b64enc | quote }}
{{- end }}
