{{- if and .Values.postgresql.enabled (not .Values.database.external.enabled) .Values.postgresql.configuration (not .Values.postgresql.customConfigMap) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "guacamole.fullname" . }}-postgresql-config
  labels:
    {{- include "guacamole.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
data:
  custom.conf: |
    {{- .Values.postgresql.configuration | nindent 4 }}
{{- end }}
