{{- if and .Values.postgresql.enabled (not .Values.database.external.enabled) (not .Values.postgresql.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "guacamole.fullname" . }}-postgresql-credentials
  labels:
    {{- include "guacamole.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.postgresql.auth.username }}
  password: {{ .Values.postgresql.auth.password | default (randAlphaNum 16) }}
{{- end }}
