{{- if and .Values.postgresql.enabled (not .Values.database.external.enabled) (not .Values.postgresql.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "guacamole.fullname" . }}-postgresql
  labels:
    {{- include "guacamole.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
type: Opaque
data:
  {{- if .Values.postgresql.auth.password }}
  password: {{ .Values.postgresql.auth.password | b64enc | quote }}
  {{- else }}
  password: {{ randAlphaNum 16 | b64enc | quote }}
  {{- end }}
{{- end }}
