{{- if and .Values.postgresql.enabled (not .Values.database.external.enabled) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "guacamole.fullname" . }}-postgresql
  labels:
    {{- include "guacamole.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
spec:
  type: {{ .Values.postgresql.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.postgresql.service.port | default 5432 }}
      targetPort: postgresql
      protocol: TCP
      name: postgresql
  selector:
    {{- include "guacamole.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
{{- end }}
