{{- if and .Values.mysql.enabled (not .Values.database.external.enabled) (not .Values.mysql.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "guacamole.fullname" . }}-mysql-credentials
  labels:
    {{- include "guacamole.labels" . | nindent 4 }}
    app.kubernetes.io/component: mysql
stringData:
  # MySQL Operator root credentials
  rootUser: root
  rootHost: "%"
  rootPassword: {{ .Values.mysql.auth.rootPassword | default (randAlphaNum 16) }}
  # Guacamole application user credentials
  username: {{ .Values.mysql.auth.username }}
  password: {{ .Values.mysql.auth.password | default (randAlphaNum 16) }}
{{- end }}
