{{- if and .Values.mysql.enabled (not .Values.database.external.enabled) (not .Values.mysql.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "guacamole.fullname" . }}-mysql
  labels:
    {{- include "guacamole.labels" . | nindent 4 }}
    app.kubernetes.io/component: mysql
type: Opaque
data:
  {{- if .Values.mysql.auth.password }}
  password: {{ .Values.mysql.auth.password | b64enc | quote }}
  {{- else }}
  password: {{ randAlphaNum 16 | b64enc | quote }}
  {{- end }}
  {{- if .Values.mysql.auth.rootPassword }}
  root-password: {{ .Values.mysql.auth.rootPassword | b64enc | quote }}
  {{- else }}
  root-password: {{ randAlphaNum 16 | b64enc | quote }}
  {{- end }}
{{- end }}
