{{- if and .Values.mysql.enabled (not .Values.database.external.enabled) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "guacamole.fullname" . }}-mysql
  labels:
    {{- include "guacamole.labels" . | nindent 4 }}
    app.kubernetes.io/component: mysql
spec:
  type: {{ .Values.mysql.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.mysql.service.port | default 3306 }}
      targetPort: mysql
      protocol: TCP
      name: mysql
  selector:
    {{- include "guacamole.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: mysql
{{- end }}
