{{- if and .Values.mariadb.enabled (not .Values.database.external.enabled) .Values.mariadb.configuration (not .Values.mariadb.customConfigMap) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "guacamole.fullname" . }}-mariadb-config
  labels:
    {{- include "guacamole.labels" . | nindent 4 }}
    app.kubernetes.io/component: mariadb
data:
  custom.cnf: |
    {{- .Values.mariadb.configuration | nindent 4 }}
{{- end }}
