{{- if and .Values.mariadb.enabled (not .Values.database.external.enabled) (not .Values.mariadb.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "guacamole.fullname" . }}-mariadb
  labels:
    {{- include "guacamole.labels" . | nindent 4 }}
    app.kubernetes.io/component: mariadb
type: Opaque
data:
  {{- if .Values.mariadb.auth.password }}
  password: {{ .Values.mariadb.auth.password | b64enc | quote }}
  {{- else }}
  password: {{ randAlphaNum 16 | b64enc | quote }}
  {{- end }}
  {{- if .Values.mariadb.auth.rootPassword }}
  root-password: {{ .Values.mariadb.auth.rootPassword | b64enc | quote }}
  {{- else }}
  root-password: {{ randAlphaNum 16 | b64enc | quote }}
  {{- end }}
{{- end }}
