{{- if and .Values.mariadb.enabled (not .Values.database.external.enabled) (not .Values.mariadb.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "guacamole.fullname" . }}-mariadb-credentials
  labels:
    {{- include "guacamole.labels" . | nindent 4 }}
    app.kubernetes.io/component: mariadb
stringData:
  root-password: {{ .Values.mariadb.auth.rootPassword | default (randAlphaNum 16) }}
  password: {{ .Values.mariadb.auth.password | default (randAlphaNum 16) }}
{{- end }}
